services:
    MKebza\Content\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']


    MKebza\Content\Service\Fixture\Provider\ImageFileProvider:
        arguments:
            $path: '%kernel.project_dir%/assets/fixture/'
        tags: ['nelmio_alice.faker.provider']


    MKebza\Content\Twig\Extension\ImageExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\ImageRuntime:
        arguments:
            $helper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            $imagineCache: '@Liip\ImagineBundle\Imagine\Cache\CacheManager'
        tags: ['twig.runtime']

    MKebza\Content\EventListener\Image\ImageMultiMapRelationListener:
        tags: ['doctrine.event_subscriber']
