services:
    _defaults:
        bind:
            $em: '@doctrine.orm.entity_manager'
            $textBlockEntityClass: '%mkebza_content.entity.text_block%'
            $galleryEntityClass: '%mkebza_content.entity.gallery%'
            $pageEntityClass: '%mkebza_content.entity.page%'

    MKebza\Content\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MKebza\Content\Service\Image\AdminImageExtension:
        tags:
            - { name: 'sonata.admin.extension' }

    MKebza\Content\Service\Fixture\Provider\ImageFileProvider:
        arguments:
            $path: '%kernel.project_dir%/assets/fixture/'
        tags: ['nelmio_alice.faker.provider']

    MKebza\Content\Service\Page\RouteLoader:
        arguments:
            $repository: '@MKebza\Content\Repository\PageRepository'
        public: true

    MKebza\Content\Twig\Extension\ImageExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\ImageRuntime:
        arguments:
            $helper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            $imagineCache: '@Liip\ImagineBundle\Imagine\Cache\CacheManager'
        tags: ['twig.runtime']

    MKebza\Content\EventListener\Image\ImageMultiMapRelationListener:
        tags: ['doctrine.event_subscriber']

    MKebza\Content\EventListener\Image\MapInheritanceListener:
        tags: ['doctrine.event_subscriber']


    MKebza\Content\Repository\TextBlockRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\GalleryRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\PageRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']


    MKebza\Content\Twig\Extension\TextBlockExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\TextBlockRuntime:
        arguments:
            $repository: '@MKebza\Content\Repository\TextBlockRepository'
        tags: ['twig.runtime']

    MKebza\Content\Service\Page\PageTypeRegistry:
        arguments:
            $types: !tagged mkebza_content.page_type

    MKebza\Content\Service\TextBlock\TextBlockTypeRegistry:
        arguments:
            $types: !tagged mkebza_content.text_block_type

    MKebza\Content\Twig\Extension\PageExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\PageRuntime:
        tags: ['twig.runtime']