services:
    _defaults:
        bind:
            $em: '@doctrine.orm.entity_manager'
            $textBlockEntityClass: '%mkebza_content.entity.text_block%'
            $galleryEntityClass: '%mkebza_content.entity.gallery%'
            $imageEntityClass: '%mkebza_content.entity.image%'
            $pageEntityClass: '%mkebza_content.entity.page%'
            $questionAnswerEntityClass: '%mkebza_content.entity.question_answer%'
            $questionAnswerCategoryEntityClass: '%mkebza_content.entity.question_answer_category%'

    MKebza\Content\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MKebza\Content\Service\Image\AdminImageExtension:
        tags:
            - { name: 'sonata.admin.extension' }

    MKebza\Content\Service\Fixture\Provider\ImageFileProvider:
        arguments:
            $path: '%kernel.project_dir%/assets/fixture/'
        tags: ['nelmio_alice.faker.provider']

    MKebza\Content\Twig\Extension\ImageExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\ImageRuntime:
        arguments:
            $helper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            $imagineCache: '@Liip\ImagineBundle\Imagine\Cache\CacheManager'
        tags: ['twig.runtime']

    MKebza\Content\Service\Image\Imager:
        arguments:
            $helper: '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            $imagineCache: '@Liip\ImagineBundle\Imagine\Cache\CacheManager'


    MKebza\Content\EventListener\Image\ImageMultiMapRelationListener:
        tags: ['doctrine.event_subscriber']

    MKebza\Content\EventListener\Image\MapInheritanceListener:
        tags: ['doctrine.event_subscriber']


    MKebza\Content\Repository\TextBlockRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\GalleryRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\PageRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\QuestionAnswerRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']

    MKebza\Content\Repository\QuestionAnswerCategoryRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags: ['doctrine.repository_service']


    MKebza\Content\Twig\Extension\TextBlockExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\TextBlockRuntime:
        arguments:
            $repository: '@MKebza\Content\Repository\TextBlockRepository'
        tags: ['twig.runtime']

    MKebza\Content\Service\Page\PageRegistry:
        arguments:
            $em: '@doctrine.orm.default_entity_manager'

    MKebza\Content\Service\Page\PageTypeRegistry:
        arguments:
            $types: !tagged mkebza_content.page_type

    MKebza\Content\Service\TextBlock\TextBlockTypeRegistry:
        arguments:
            $types: !tagged mkebza_content.text_block_type

    MKebza\Content\Twig\Extension\PageExtension:
        tags: ['twig.extension']

    MKebza\Content\Twig\Runtime\PageRuntime:
        tags: ['twig.runtime']

    MKebza\Content\Service\VichUploader\ImageDirectoryNamer:
        public: true # Because of vich uploader

    MKebza\Content\Service\VichUploader\ImageNamer:
        public: true # Because of vich uploader
        arguments:
            $slugify: '@slugify'

    MKebza\Content\Service\Sitemap\PageGenerator:
        arguments:
            $router: '@router'
            $repository: '@MKebza\Content\Repository\PageRepository'
        tags: ['mkebza_sitemap.generator']


    MKebza\Content\Service\Image\ImageCreator: ~
    MKebza\Content\Service\TextBlock\TextBlockCreator: ~
    mkebza_content.text_block.creator:
        alias: MKebza\Content\Service\TextBlock\TextBlockCreator
        public: true

    MKebza\Content\Service\Page\PageCreator: ~
    mkebza_content.page.creator:
        alias: MKebza\Content\Service\Page\PageCreator
        public: true

    MKebza\Content\Service\Gallery\GalleryCreator: ~
    mkebza_content.gallery.creator:
        alias: MKebza\Content\Service\Gallery\GalleryCreator
        public: true

    vich_uploader.storage.flysystem_overwriting:
        class: MKebza\Content\Service\VichUploader\OverwritingFlysystemStorage
        public: true
        arguments:
            - '@vich_uploader.property_mapping_factory'
            - '@oneup_flysystem.mount_manager'

    vich_uploader.namer_subdir:
        class: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
        public: true