services:
    sonata.admin.image:
        class: MKebza\Content\Admin\ImageAdmin
        arguments: [~, App\Entity\Content\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true, group: 'Content', label: 'Images', icon: '<i class="fa fa-file-text"></i>' }
