services:
#    sonata.admin.image:
#        class: MKebza\Content\Admin\ImageAdmin
#        arguments:
#            - ~
#            - App\Entity\Accommodation\AccommodationImage
#            - MKebza\Content\Controller\ImageController
#        tags:
#            -
#                name: sonata.admin
#                manager_type: orm
#                show_in_dashboard: true
#                group: 'Content'
#                label: 'Images'
#                icon: '<i class="fa fa-file-text"></i>'
#                show_mosaic_button: true
