services:
    sonata.admin.page:
        class: MKebza\Content\Admin\PageAdmin
        arguments:
            - ~
            - '%mkebza_content.entity.page%'
            - ~
        calls:
            - ['setPageTypeRegistry', ['@MKebza\Content\Service\Page\PageTypeRegistry']]
            - ['addChild', ['@sonata.admin.page.log', 'reference']]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'Content'
                label: 'Page'
                icon: '<i class="fa fa-file-text"></i>'

    sonata.admin.page.log:
        class: MKebza\Content\Admin\PageLogAdmin
        arguments:
            - ~
            - MKebza\Content\Entity\PageLog
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: false

