services:
    sonata.admin.question_answer:
        class: MKebza\Content\Admin\QuestionAnswerAdmin
        arguments:
            - ~
            - '%mkebza_content.entity.question_answer%'
            - ~
        calls:
            - ['addChild', ['@sonata.admin.question_answer.log', 'reference']]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'menu.group.content'
                label: 'menu.item.questionsAnswers'
                icon: '<i class="fa fa-file-text"></i>'

    sonata.admin.question_answer.log:
        class: MKebza\SonataExt\Admin\LogReferenceAdmin
        arguments:
            - ~
            - MKebza\Content\Entity\QuestionAnswerLog
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: false


    sonata.admin.question_answer_category:
        class: MKebza\Content\Admin\QuestionAnswerCategoryAdmin
        arguments:
            - ~
            - '%mkebza_content.entity.question_answer_category%'
            - ~
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'menu.group.content'
                label: 'menu.item.questionsAnswersCategories'
                icon: '<i class="fa fa-file-text"></i>'

