services:
    sonata.admin.question_answer:
        class: MKebza\Content\Admin\QuestionAnswerAdmin
        arguments:
        - ~
        - '%mkebza_content.entity.question_answer%'
        - ~
        #        calls:
        #            - ['addChild', ['@sonata.admin.page.log', 'reference']]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'Content'
                label: 'QA'
                icon: '<i class="fa fa-file-text"></i>'


    sonata.admin.question_answer_category:
        class: MKebza\Content\Admin\QuestionAnswerCategoryAdmin
        arguments:
            - ~
            - '%mkebza_content.entity.question_answer_category%'
            - ~
#        calls:
#            - ['addChild', ['@sonata.admin.page.log', 'reference']]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                show_in_dashboard: true
                group: 'Content'
                label: 'QA - Category'
                icon: '<i class="fa fa-file-text"></i>'

#    sonata.admin.page.log:
#        class: MKebza\SonataExt\Admin\LogReferenceAdmin
#        arguments:
#            - ~
#            - MKebza\Content\Entity\PageLog
#            - ~
#        tags:
#            -
#                name: sonata.admin
#                manager_type: orm
#                show_in_dashboard: false

